# Generated by Django 4.1.7 on 2023-05-14 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Добавить документ',
                'verbose_name_plural': 'Добавить документ',
            },
        ),
        migrations.CreateModel(
            name='R1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R1',
                'verbose_name_plural': 'R1',
            },
        ),
        migrations.CreateModel(
            name='R10_R11_R13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R10_R11_R13',
                'verbose_name_plural': 'R10_R11_R13',
            },
        ),
        migrations.CreateModel(
            name='R12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R12',
                'verbose_name_plural': 'R12',
            },
        ),
        migrations.CreateModel(
            name='R14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R14',
                'verbose_name_plural': 'R14',
            },
        ),
        migrations.CreateModel(
            name='R15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R15',
                'verbose_name_plural': 'R15',
            },
        ),
        migrations.CreateModel(
            name='R16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R16',
                'verbose_name_plural': 'R16',
            },
        ),
        migrations.CreateModel(
            name='R17',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R17',
                'verbose_name_plural': 'R17',
            },
        ),
        migrations.CreateModel(
            name='R18',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R18',
                'verbose_name_plural': 'R18',
            },
        ),
        migrations.CreateModel(
            name='R19',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R19',
                'verbose_name_plural': 'R19',
            },
        ),
        migrations.CreateModel(
            name='R2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R2',
                'verbose_name_plural': 'R2',
            },
        ),
        migrations.CreateModel(
            name='R20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R20',
                'verbose_name_plural': 'R20',
            },
        ),
        migrations.CreateModel(
            name='R21',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R21',
                'verbose_name_plural': 'R21',
            },
        ),
        migrations.CreateModel(
            name='R22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R22',
                'verbose_name_plural': 'R22',
            },
        ),
        migrations.CreateModel(
            name='R23',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R23',
                'verbose_name_plural': 'R23',
            },
        ),
        migrations.CreateModel(
            name='R24',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R24',
                'verbose_name_plural': 'R24',
            },
        ),
        migrations.CreateModel(
            name='R25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R25',
                'verbose_name_plural': 'R25',
            },
        ),
        migrations.CreateModel(
            name='R3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R3',
                'verbose_name_plural': 'R3',
            },
        ),
        migrations.CreateModel(
            name='R4_R5_R6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R4_R5_R6',
                'verbose_name_plural': 'R4_R5_R6',
            },
        ),
        migrations.CreateModel(
            name='R7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R7',
                'verbose_name_plural': 'R7',
            },
        ),
        migrations.CreateModel(
            name='R8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R8',
                'verbose_name_plural': 'R8',
            },
        ),
        migrations.CreateModel(
            name='R9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R9',
                'verbose_name_plural': 'R9',
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Регионы и области')),
            ],
            options={
                'verbose_name': 'Регионы и области',
                'verbose_name_plural': 'Регионы и области',
            },
        ),
        migrations.CreateModel(
            name='VR9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField(verbose_name='Всего')),
                ('value2', models.IntegerField(blank=True, null=True, verbose_name='Высшее образование')),
                ('value3', models.IntegerField(blank=True, null=True, verbose_name='Высшее педагогическое образование')),
                ('value4', models.IntegerField(blank=True, null=True, verbose_name='Среднее профессиональное образование по программам подготовки специалистов среднего звена')),
                ('value5', models.IntegerField(blank=True, null=True, verbose_name='среднее профессиональное педагогическое образование')),
                ('value6', models.IntegerField(verbose_name='Всего женщин')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builddocs', verbose_name='Документ')),
                ('r9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r9', verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'VR9',
                'verbose_name_plural': 'VR9',
            },
        ),
        migrations.CreateModel(
            name='VR8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField(verbose_name='Численность воспитанников')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builddocs', verbose_name='Документ')),
                ('r8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r8', verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'VR8',
                'verbose_name_plural': 'VR8',
            },
        ),
        migrations.CreateModel(
            name='VR7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField(verbose_name='Всего')),
                ('value2', models.IntegerField(verbose_name='0 лет')),
                ('value3', models.IntegerField(verbose_name='1 год')),
                ('value4', models.IntegerField(verbose_name='2 года')),
                ('value5', models.IntegerField(verbose_name='3 года')),
                ('value6', models.IntegerField(verbose_name='4 лет')),
                ('value7', models.IntegerField(verbose_name='5 лет')),
                ('value8', models.IntegerField(verbose_name='6 лет')),
                ('value9', models.IntegerField(verbose_name='7 лет и старше')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builddocs', verbose_name='Документ')),
                ('r7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r7', verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'VR7',
                'verbose_name_plural': 'VR7',
            },
        ),
        migrations.CreateModel(
            name='VR6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField(verbose_name='Всего групп')),
                ('value2', models.IntegerField(verbose_name='от 2-х месяцев до 1 года')),
                ('value3', models.IntegerField(verbose_name='от 1 года до 3-х лет')),
                ('value4', models.IntegerField(verbose_name='от 3-х до 5 лет')),
                ('value5', models.IntegerField(verbose_name='5 лет и старше')),
                ('value6', models.IntegerField(verbose_name='разновозрастные')),
                ('value7', models.IntegerField(verbose_name='с ограниченными возможностями здоровья')),
                ('value8', models.IntegerField(verbose_name='из них дети-инвалиды')),
                ('value9', models.IntegerField(verbose_name='дети-инвалиды, не учтенные в группах')),
                ('value10', models.IntegerField(verbose_name='имеющие иностранное гражданство или имеющие несколько гражданств')),
                ('value11', models.IntegerField(verbose_name='без гражданства')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builddocs', verbose_name='Документ')),
                ('r6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r4_r5_r6', verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'VR6',
                'verbose_name_plural': 'VR6',
            },
        ),
        migrations.CreateModel(
            name='VR5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField(verbose_name='Всего групп')),
                ('value2', models.IntegerField(verbose_name='от 2-х месяцев до 1 года')),
                ('value3', models.IntegerField(verbose_name='от 1 года до 3-х лет')),
                ('value4', models.IntegerField(verbose_name='от 3-х до 5 лет')),
                ('value5', models.IntegerField(verbose_name='5 лет и старше')),
                ('value6', models.IntegerField(verbose_name='разновозрастные')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builddocs', verbose_name='Документ')),
                ('r5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r4_r5_r6', verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'VR5',
                'verbose_name_plural': 'VR5',
            },
        ),
        migrations.CreateModel(
            name='VR4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField(verbose_name='Всего групп')),
                ('value2', models.IntegerField(verbose_name='от 2-х месяцев до 1 года')),
                ('value3', models.IntegerField(verbose_name='от 1 года до 3-х лет')),
                ('value4', models.IntegerField(verbose_name='от 3-х до 5 лет')),
                ('value5', models.IntegerField(verbose_name='5 лет и старше')),
                ('value6', models.IntegerField(verbose_name='разновозрастные')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builddocs', verbose_name='Документ')),
                ('r4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r4_r5_r6', verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'VR4',
                'verbose_name_plural': 'VR4',
            },
        ),
        migrations.CreateModel(
            name='VR3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField(blank=True, null=True, verbose_name='Всего реализуемых образовательных программ')),
                ('value2', models.IntegerField(blank=True, null=True, verbose_name='Число образовательных программ реализуемых с использованием сетевой формы')),
                ('value3', models.IntegerField(blank=True, null=True, verbose_name='Общее число заключенных договоров с организациями на реализацию образовательных программ с использованием сетевой формы')),
                ('value4', models.IntegerField(blank=True, null=True, verbose_name='Численность воспитанников, обучающихся с применением сетевой формы')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builddocs', verbose_name='Документ')),
                ('r3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r3', verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'VR3',
                'verbose_name_plural': 'VR3',
            },
        ),
        migrations.CreateModel(
            name='VR25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField(blank=True, null=True, verbose_name='Всего')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builddocs', verbose_name='Документ')),
                ('r25', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r25', verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'VR25',
                'verbose_name_plural': 'VR25',
            },
        ),
        migrations.CreateModel(
            name='VR24',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField(blank=True, null=True, verbose_name='Всего')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builddocs', verbose_name='Документ')),
                ('r24', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r24', verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'VR24',
                'verbose_name_plural': 'VR24',
            },
        ),
        migrations.CreateModel(
            name='VR23',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField(blank=True, null=True, verbose_name='Средняя численность работников списочного состава (без внешних совместителей)')),
                ('value2', models.IntegerField(blank=True, null=True, verbose_name='Средняя численность работников внешних совместителей')),
                ('value3', models.IntegerField(blank=True, null=True, verbose_name='Фонд начисленной заработной платы работников, тыс. руб, списочного состава (без внешних совместителей) Всего')),
                ('value4', models.IntegerField(blank=True, null=True, verbose_name='Фонд начисленной заработной платы работников, тыс. руб, списочного состава (без внешних совместителей) в том числе по внутреннему совместительству')),
                ('value5', models.IntegerField(blank=True, null=True, verbose_name='Фонд начисленной заработной платы работников, тыс. руб, внешних совместителей')),
                ('value6', models.IntegerField(blank=True, null=True, verbose_name='Фонд начисленной заработной платы работников по источникам финансирования из всего списочного состава (без внешних совместителей) за счет средств бюджетов всех уровней (субсидий)')),
                ('value7', models.IntegerField(blank=True, null=True, verbose_name='Фонд начисленной заработной платы работников по источникам финансирования из всего списочного состава (без внешних совместителей) ОМС')),
                ('value8', models.IntegerField(blank=True, null=True, verbose_name='Фонд начисленной заработной платы работников по источникам финансирования из всего списочного состава (без внешних совместителей) средства от приносящей доход деятельности')),
                ('value9', models.IntegerField(blank=True, null=True, verbose_name='Фонд начисленной заработной платы работников по источникам финансирования из внешних совместителей за счет средств бюджетов всех уровней (субсидий)')),
                ('value10', models.IntegerField(blank=True, null=True, verbose_name='Фонд начисленной заработной платы работников по источникам финансирования из внешних совместителей ОМС')),
                ('value11', models.IntegerField(blank=True, null=True, verbose_name='Фонд начисленной заработной платы работников по источникам финансирования из внешних совместителей средства от приносящей доход деятельности')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builddocs', verbose_name='Документ')),
                ('r23', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r23', verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'VR23',
                'verbose_name_plural': 'VR23',
            },
        ),
        migrations.CreateModel(
            name='VR22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField(blank=True, null=True, verbose_name='Всего')),
                ('value2', models.IntegerField(blank=True, null=True, verbose_name='из них осуществляемые за счет средств бюджетов всех уровней (субсидий)')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builddocs', verbose_name='Документ')),
                ('r22', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r22', verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'VR22',
                'verbose_name_plural': 'VR22',
            },
        ),
        migrations.CreateModel(
            name='VR21',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField(blank=True, null=True, verbose_name='Всего')),
                ('value2', models.IntegerField(blank=True, null=True, verbose_name='из них по образовательной деятельности')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builddocs', verbose_name='Документ')),
                ('r21', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r21', verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'VR21',
                'verbose_name_plural': 'VR21',
            },
        ),
        migrations.CreateModel(
            name='VR20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField(blank=True, null=True, verbose_name='Всего')),
                ('value2', models.IntegerField(blank=True, null=True, verbose_name='в том числе доступные для использования воспитанниками')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builddocs', verbose_name='Документ')),
                ('r20', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r20', verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'VR20',
                'verbose_name_plural': 'VR20',
            },
        ),
        migrations.CreateModel(
            name='VR2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Численность воспитанников, чел.')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builddocs', verbose_name='Документ')),
                ('r2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r2', verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'VR2',
                'verbose_name_plural': 'VR2',
            },
        ),
        migrations.CreateModel(
            name='VR19',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField(blank=True, null=True, verbose_name='Наличие в организации, код: да - 1, нет - 2')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builddocs', verbose_name='Документ')),
                ('r19', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r19', verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'VR19',
                'verbose_name_plural': 'VR19',
            },
        ),
        migrations.CreateModel(
            name='VR18',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField(blank=True, null=True, verbose_name='Наличие в организации, код: да - 1, нет - 2')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builddocs', verbose_name='Документ')),
                ('r18', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r18', verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'VR18',
                'verbose_name_plural': 'VR18',
            },
        ),
        migrations.CreateModel(
            name='VR17',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField(blank=True, null=True, verbose_name='Всего')),
                ('value2', models.IntegerField(blank=True, null=True, verbose_name='Площадь, сданная в аренду и/или субаренду')),
                ('value3', models.IntegerField(blank=True, null=True, verbose_name='Площадь на правах собственности')),
                ('value4', models.IntegerField(blank=True, null=True, verbose_name='Площадь в оперативном управлении')),
                ('value5', models.IntegerField(blank=True, null=True, verbose_name='Арендованная площадь')),
                ('value6', models.IntegerField(blank=True, null=True, verbose_name='Площадь в другой форме владения')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builddocs', verbose_name='Документ')),
                ('r17', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r17', verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'VR17',
                'verbose_name_plural': 'VR17',
            },
        ),
        migrations.CreateModel(
            name='VR16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField(blank=True, null=True, verbose_name='Наличие в организации, код: да - 1, нет - 2')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builddocs', verbose_name='Документ')),
                ('r16', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r16', verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'VR16',
                'verbose_name_plural': 'VR16',
            },
        ),
        migrations.CreateModel(
            name='VR15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField(blank=True, null=True, verbose_name='Стены здания: каменные')),
                ('value2', models.IntegerField(blank=True, null=True, verbose_name='Стены здания: кирпичные')),
                ('value3', models.IntegerField(blank=True, null=True, verbose_name='Стены здания: панельные')),
                ('value4', models.IntegerField(blank=True, null=True, verbose_name='Стены здания: блочные')),
                ('value5', models.IntegerField(blank=True, null=True, verbose_name='Стены здания: деревянные')),
                ('value6', models.IntegerField(blank=True, null=True, verbose_name='Стены здания: монолитные')),
                ('value7', models.IntegerField(blank=True, null=True, verbose_name='Стены здания: смешанные')),
                ('value8', models.IntegerField(blank=True, null=True, verbose_name='Стены здания: из прочих стеновых материалов')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builddocs', verbose_name='Документ')),
                ('r15', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r15', verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'VR15',
                'verbose_name_plural': 'VR15',
            },
        ),
        migrations.CreateModel(
            name='VR14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField(blank=True, null=True, verbose_name='Всего')),
                ('value2', models.IntegerField(blank=True, null=True, verbose_name='Оборудовано водопроводом')),
                ('value3', models.IntegerField(blank=True, null=True, verbose_name='Оборудовано водоотведением (канализацией)')),
                ('value4', models.IntegerField(blank=True, null=True, verbose_name='Оборудовано центральным отоплением')),
                ('value5', models.IntegerField(blank=True, null=True, verbose_name='Оборудовано системой видеонаблюдения')),
                ('value6', models.IntegerField(blank=True, null=True, verbose_name='Требует капитального ремонта')),
                ('value7', models.IntegerField(blank=True, null=True, verbose_name='Находится в аварийном состоянии')),
                ('value8', models.IntegerField(blank=True, null=True, verbose_name='Имеет охрану')),
                ('value9', models.IntegerField(blank=True, null=True, verbose_name='Оборудовано автоматической пожарной сигнализацией')),
                ('value10', models.IntegerField(blank=True, null=True, verbose_name='Имеет дымовые извещатели')),
                ('value11', models.IntegerField(blank=True, null=True, verbose_name='Имеет пожарные краны и рукава')),
                ('value12', models.IntegerField(blank=True, null=True, verbose_name='Оборудовано кнопкой тревожной сигнализации')),
                ('value13', models.IntegerField(blank=True, null=True, verbose_name='Доступно для маломобильных групп населения')),
                ('value14', models.IntegerField(blank=True, null=True, verbose_name='Скорость Интернета ниже 256 Кбит/сек')),
                ('value15', models.IntegerField(blank=True, null=True, verbose_name='Скорость Интернета 256 - 511 Кбит/сек')),
                ('value16', models.IntegerField(blank=True, null=True, verbose_name='Скорость Интернета 512 Кбит/сек - 999 Кбит/сек')),
                ('value17', models.IntegerField(blank=True, null=True, verbose_name='Скорость Интернета 1.0 - 1.9 Мбит/сек')),
                ('value18', models.IntegerField(blank=True, null=True, verbose_name='Скорость Интернета 2.0 - 29.9 Мбит/сек')),
                ('value19', models.IntegerField(blank=True, null=True, verbose_name='Скорость Интернета 30.0 - 49.9 Мбит/сек')),
                ('value20', models.IntegerField(blank=True, null=True, verbose_name='Скорость Интернета 50.0 - 99.9 Мбит/сек')),
                ('value21', models.IntegerField(blank=True, null=True, verbose_name='Скорость Интернета 100 Мбит/сек и выше')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builddocs', verbose_name='Документ')),
                ('r14', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r14', verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'VR14',
                'verbose_name_plural': 'VR14',
            },
        ),
        migrations.CreateModel(
            name='VR13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField(verbose_name='Число ставок по штату, ед.')),
                ('value2', models.IntegerField(verbose_name='Всего фактически занято')),
                ('value3', models.IntegerField(verbose_name='Фактически занято работниками списочного состава')),
                ('value4', models.IntegerField(verbose_name='Численность работников на начало отчетного года (без внешних совместителей и работающих по договорам гражданско- правового характера)')),
                ('value5', models.IntegerField(verbose_name='Всего принято работников')),
                ('value6', models.IntegerField(verbose_name='Принято работников, являющимися выпускниками со средним профессиональным образованием по программам подготовки специалистов среднего звена')),
                ('value7', models.IntegerField(verbose_name='Принято работников, являющимися выпускниками с высшим образованием')),
                ('value8', models.IntegerField(verbose_name='Всего выбыло работников')),
                ('value9', models.IntegerField(verbose_name='Выбыло работников по собственному желанию')),
                ('value10', models.IntegerField(verbose_name='Численность работников на конец отчетного года (без совместителей и работающих по договорам гражданско-правового характера)')),
                ('value11', models.IntegerField(verbose_name='Число вакантных должностей')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builddocs', verbose_name='Документ')),
                ('r13', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r10_r11_r13', verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'VR13',
                'verbose_name_plural': 'VR13',
            },
        ),
        migrations.CreateModel(
            name='VR12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField(verbose_name='Всего')),
                ('value2', models.IntegerField(verbose_name='Всего женщин')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builddocs', verbose_name='Документ')),
                ('r12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r12', verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'VR12',
                'verbose_name_plural': 'VR12',
            },
        ),
        migrations.CreateModel(
            name='VR11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField(verbose_name='Всего с общим стажем')),
                ('value2', models.IntegerField(verbose_name='с общим стажем до 3 лет')),
                ('value3', models.IntegerField(verbose_name='с общим стажем от 3 до 5 лет')),
                ('value4', models.IntegerField(verbose_name='с общим стажем от 5 до 10 лет')),
                ('value5', models.IntegerField(verbose_name='с общим стажем от 10 до 15 лет')),
                ('value6', models.IntegerField(verbose_name='с общим стажем от 15 до 20 лет')),
                ('value7', models.IntegerField(verbose_name='с общим стажем от 20 и более лет')),
                ('value8', models.IntegerField(verbose_name='Из общей численности работников имеют педагогический стаж (всего)')),
                ('value9', models.IntegerField(verbose_name='с педагогическим стажем до 3 лет')),
                ('value10', models.IntegerField(verbose_name='с педагогическим стажем от 3 до 5 лет')),
                ('value11', models.IntegerField(verbose_name='с педагогическим стажем от 5 до 10 лет')),
                ('value12', models.IntegerField(verbose_name='с педагогическим стажем от 10 до 15 лет')),
                ('value13', models.IntegerField(verbose_name='с педагогическим стажем от 15 до 20 лет')),
                ('value14', models.IntegerField(verbose_name='с педагогическим стажем от 20 и более лет')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builddocs', verbose_name='Документ')),
                ('r11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r10_r11_r13', verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'VR11',
                'verbose_name_plural': 'VR11',
            },
        ),
        migrations.CreateModel(
            name='VR10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.IntegerField(verbose_name='Всего')),
                ('value2', models.IntegerField(verbose_name='моложе 25 лет')),
                ('value3', models.IntegerField(verbose_name='25-29')),
                ('value4', models.IntegerField(verbose_name='30-34')),
                ('value5', models.IntegerField(verbose_name='35-39')),
                ('value6', models.IntegerField(verbose_name='40-44')),
                ('value7', models.IntegerField(verbose_name='45-49')),
                ('value8', models.IntegerField(verbose_name='50-54')),
                ('value9', models.IntegerField(verbose_name='55-59')),
                ('value10', models.IntegerField(verbose_name='60-64')),
                ('value11', models.IntegerField(verbose_name='65 и старше')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builddocs', verbose_name='Документ')),
                ('r10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r10_r11_r13', verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'VR10',
                'verbose_name_plural': 'VR10',
            },
        ),
        migrations.CreateModel(
            name='VR1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='код')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builddocs', verbose_name='Документ')),
                ('r1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r1', verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'VR1',
                'verbose_name_plural': 'VR1',
            },
        ),
        migrations.CreateModel(
            name='Builds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=300, verbose_name='Наименование оганизации')),
                ('id_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.regions', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.AddField(
            model_name='builddocs',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builds', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='builddocs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
