# Generated by Django 4.1.7 on 2023-05-10 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Builds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=300, verbose_name='Наименование оганизации')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название мероприятия', max_length=50, verbose_name='Название')),
                ('desctiption', models.TextField(blank=True, help_text='Описание мероприятия', null=True, verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, help_text='Логотип мероприятия', max_length=50, upload_to='images/', verbose_name='Логотип')),
                ('status_event', models.CharField(choices=[('1', 'Не началось'), ('2', 'В процессе'), ('3', 'Закончилось')], default='1', help_text='Статус мероприятия', max_length=1, verbose_name='Статус')),
                ('data_start', models.DateField(help_text='Дата начала мероприятия', null=True, verbose_name='Дата начала')),
                ('data_end', models.DateField(help_text='Дата конца мероприятия', null=True, verbose_name='Дата конца')),
                ('city', models.TextField(help_text='Город проведения мероприятия', max_length=50, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='R10R11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R10R11',
                'verbose_name_plural': 'R10R11',
            },
        ),
        migrations.CreateModel(
            name='R12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R12',
                'verbose_name_plural': 'R12',
            },
        ),
        migrations.CreateModel(
            name='R13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R13',
                'verbose_name_plural': 'R13',
            },
        ),
        migrations.CreateModel(
            name='R14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R14',
                'verbose_name_plural': 'R14',
            },
        ),
        migrations.CreateModel(
            name='R16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'R16',
                'verbose_name_plural': 'R16',
            },
        ),
        migrations.CreateModel(
            name='R17',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R17',
                'verbose_name_plural': 'R17',
            },
        ),
        migrations.CreateModel(
            name='R18',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'R18',
                'verbose_name_plural': 'R18',
            },
        ),
        migrations.CreateModel(
            name='R19',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'R19',
                'verbose_name_plural': 'R19',
            },
        ),
        migrations.CreateModel(
            name='R2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Режим работы')),
            ],
            options={
                'verbose_name': 'R2',
                'verbose_name_plural': 'R2',
            },
        ),
        migrations.CreateModel(
            name='R20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'R20',
                'verbose_name_plural': 'R20',
            },
        ),
        migrations.CreateModel(
            name='R21',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'R21',
                'verbose_name_plural': 'R21',
            },
        ),
        migrations.CreateModel(
            name='R22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'R22',
                'verbose_name_plural': 'R22',
            },
        ),
        migrations.CreateModel(
            name='R23',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R23',
                'verbose_name_plural': 'R23',
            },
        ),
        migrations.CreateModel(
            name='R24',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'R24',
                'verbose_name_plural': 'R24',
            },
        ),
        migrations.CreateModel(
            name='R25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'R25',
                'verbose_name_plural': 'R25',
            },
        ),
        migrations.CreateModel(
            name='R3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование программ')),
            ],
            options={
                'verbose_name': 'R3',
                'verbose_name_plural': 'R3',
            },
        ),
        migrations.CreateModel(
            name='R4R5R6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R4R5',
                'verbose_name_plural': 'R4R5',
            },
        ),
        migrations.CreateModel(
            name='R7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование программ')),
            ],
            options={
                'verbose_name': 'R7',
                'verbose_name_plural': 'R7',
            },
        ),
        migrations.CreateModel(
            name='R8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R8',
                'verbose_name_plural': 'R8',
            },
        ),
        migrations.CreateModel(
            name='R9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование показателей')),
            ],
            options={
                'verbose_name': 'R9',
                'verbose_name_plural': 'R9',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Роль человека на мероприятии', max_length=50, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='TitleDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=20, verbose_name='Почтовый адрес')),
                ('year', models.IntegerField(verbose_name='Год подачии документа: 202_г')),
                ('date1', models.DateField(blank=True, null=True, verbose_name='О внесении изменений (при наличии) от')),
                ('date1_id', models.IntegerField(blank=True, null=True, verbose_name='№')),
                ('date2', models.DateField(blank=True, null=True, verbose_name='О внесении изменений (при наличии) от')),
                ('date2_id', models.IntegerField(blank=True, null=True, verbose_name='№')),
                ('okud_code', models.CharField(default='0609506', max_length=7, verbose_name='Код формы по ОКУД')),
                ('okpo_code', models.CharField(max_length=15, verbose_name='Код отчитывающейся организации по ОКПО (для обособленного подразделения и головного подразделения юридического лица - идентификационный номер)')),
                ('link', models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='Документ')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builds', verbose_name='Событие в котором учавствует пользователь')),
            ],
            options={
                'verbose_name': 'Титульный лист',
                'verbose_name_plural': 'Титульные листы',
            },
        ),
        migrations.CreateModel(
            name='VR9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(max_length=4, verbose_name='№ строки')),
                ('value1', models.IntegerField(verbose_name='Всего')),
                ('value2', models.CharField(max_length=5, verbose_name='высшее')),
                ('value3', models.CharField(max_length=5, verbose_name='из них педагогическое')),
                ('value4', models.CharField(max_length=5, verbose_name='среднее профессиональное образование по программам подготовки специалистов среднего звена')),
                ('value5', models.CharField(max_length=5, verbose_name='из них педагогическое')),
                ('value6', models.IntegerField(verbose_name='всего женщин')),
                ('r9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r9', verbose_name='Наименование показателей')),
                ('title_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.titledoc', verbose_name='Шапка документа')),
            ],
            options={
                'verbose_name': 'VR9',
                'verbose_name_plural': 'VR9',
            },
        ),
        migrations.CreateModel(
            name='VR8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(max_length=4, verbose_name='№ строки')),
                ('value1', models.CharField(max_length=3, verbose_name='Код языка по Общероссийскому классификатору информации о населении (ОКИН)')),
                ('value2', models.IntegerField(verbose_name='Численность воспитанников')),
                ('r8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r8', verbose_name='Наименование показателей')),
                ('title_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.titledoc', verbose_name='Шапка документа')),
            ],
            options={
                'verbose_name': 'VR8',
                'verbose_name_plural': 'VR8',
            },
        ),
        migrations.CreateModel(
            name='VR7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(max_length=4, verbose_name='№ строки')),
                ('value1', models.IntegerField(verbose_name='Всего')),
                ('value2', models.IntegerField(verbose_name='0 лет')),
                ('value3', models.IntegerField(verbose_name='1 год')),
                ('value4', models.IntegerField(verbose_name='2 года')),
                ('value5', models.IntegerField(verbose_name='3 года')),
                ('value6', models.IntegerField(verbose_name='4 лет')),
                ('value7', models.IntegerField(verbose_name='5 лет')),
                ('value8', models.IntegerField(verbose_name='6 лет')),
                ('value9', models.IntegerField(verbose_name='7 лет и старше')),
                ('r7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r7', verbose_name='Наименование показателей')),
                ('title_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.titledoc', verbose_name='Шапка документа')),
            ],
            options={
                'verbose_name': 'VR7',
                'verbose_name_plural': 'VR7',
            },
        ),
        migrations.CreateModel(
            name='VR6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(max_length=4, verbose_name='№ строки')),
                ('value1', models.IntegerField(verbose_name='Всего детей в группах')),
                ('value2', models.IntegerField(verbose_name='от 2-х месяцев до 1 года')),
                ('value3', models.IntegerField(verbose_name='от 1 года до 3-х лет')),
                ('value4', models.IntegerField(verbose_name='от 3-х до 5 лет')),
                ('value5', models.IntegerField(verbose_name='5 лет и старше')),
                ('value6', models.IntegerField(verbose_name='разновозрастные')),
                ('value7', models.IntegerField(verbose_name='с ограниченными возможностями здоровья')),
                ('value8', models.IntegerField(verbose_name='из них дети-инвалиды')),
                ('value9', models.IntegerField(verbose_name='дети-инвалиды, не учтенные в группах')),
                ('value10', models.IntegerField(verbose_name='имеющие иностранное гражданство или имеющие несколько гражданств')),
                ('value11', models.IntegerField(verbose_name='без гражданства')),
                ('r6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r4r5r6', verbose_name='Наименование показателей')),
                ('title_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.titledoc', verbose_name='Шапка документа')),
            ],
            options={
                'verbose_name': 'VR6',
                'verbose_name_plural': 'VR6',
            },
        ),
        migrations.CreateModel(
            name='VR5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(max_length=4, verbose_name='№ строки')),
                ('value1', models.IntegerField(verbose_name='Всего мест в группах')),
                ('value2', models.IntegerField(verbose_name='от 2-х месяцев до 1 года')),
                ('value3', models.IntegerField(verbose_name='от 1 года до 3-х лет')),
                ('value4', models.IntegerField(verbose_name='от 3-х до 5 лет')),
                ('value5', models.IntegerField(verbose_name='5 лет и старше')),
                ('value6', models.IntegerField(verbose_name='разновозрастные')),
                ('r5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r4r5r6', verbose_name='Наименование показателей')),
                ('title_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.titledoc', verbose_name='Шапка документа')),
            ],
            options={
                'verbose_name': 'VR5',
                'verbose_name_plural': 'VR5',
            },
        ),
        migrations.CreateModel(
            name='VR4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(max_length=4, verbose_name='№ строки')),
                ('value1', models.IntegerField(verbose_name='Всего групп')),
                ('value2', models.IntegerField(verbose_name='от 2-х месяцев до 1 года')),
                ('value3', models.IntegerField(verbose_name='от 1 года до 3-х лет')),
                ('value4', models.IntegerField(verbose_name='от 3-х до 5 лет')),
                ('value5', models.IntegerField(verbose_name='5 лет и старше')),
                ('value6', models.IntegerField(verbose_name='разновозрастные')),
                ('r4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r4r5r6', verbose_name='Наименование показателей')),
                ('title_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.titledoc', verbose_name='Шапка документа')),
            ],
            options={
                'verbose_name': 'VR4',
                'verbose_name_plural': 'VR4',
            },
        ),
        migrations.CreateModel(
            name='VR3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(max_length=4, verbose_name='№ строки')),
                ('value1', models.IntegerField(verbose_name='Всего реализуемых образовательных программ')),
                ('value2', models.IntegerField(verbose_name='Число образовательных программ реализуемых с использованием сетевой формы')),
                ('value3', models.IntegerField(verbose_name='Общее число заключенных договоров с организациями на реализацию образовательных программ с использованием сетевой формы')),
                ('value4', models.IntegerField(verbose_name='Численность воспитанников, обучающихся с применением сетевой формы')),
                ('r3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r3', verbose_name='Наименование программ')),
                ('title_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.titledoc', verbose_name='Шапка документа')),
            ],
            options={
                'verbose_name': 'VR3',
                'verbose_name_plural': 'VR3',
            },
        ),
        migrations.CreateModel(
            name='VR25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(max_length=4, verbose_name='№ строки')),
                ('value1', models.IntegerField(blank=True, null=True, verbose_name='Всего')),
                ('r25', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r25', verbose_name='Наименование')),
                ('title_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.titledoc', verbose_name='Шапка документа')),
            ],
            options={
                'verbose_name': 'VR25',
                'verbose_name_plural': 'VR25',
            },
        ),
        migrations.CreateModel(
            name='VR24',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(max_length=4, verbose_name='№ строки')),
                ('value1', models.IntegerField(blank=True, null=True, verbose_name='Всего')),
                ('r24', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r24', verbose_name='Наименование')),
                ('title_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.titledoc', verbose_name='Шапка документа')),
            ],
            options={
                'verbose_name': 'VR24',
                'verbose_name_plural': 'VR24',
            },
        ),
        migrations.CreateModel(
            name='VR23',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(max_length=4, verbose_name='№ строки')),
                ('value1', models.IntegerField(blank=True, null=True, verbose_name='Средняя численность работников списочного состава (без внешних совместителей)')),
                ('value2', models.IntegerField(blank=True, null=True, verbose_name='Средняя численность работников внешних совместителей')),
                ('value3', models.IntegerField(blank=True, null=True, verbose_name='Фонд начисленной заработной платы работников, тыс. руб, списочного состава (без внешних совместителей) Всего')),
                ('value4', models.IntegerField(blank=True, null=True, verbose_name='Фонд начисленной заработной платы работников, тыс. руб, списочного состава (без внешних совместителей) в том числе по внутреннему совместительству')),
                ('value5', models.IntegerField(blank=True, null=True, verbose_name='Фонд начисленной заработной платы работников, тыс. руб, внешних совместителей')),
                ('value6', models.IntegerField(blank=True, null=True, verbose_name='Фонд начисленной заработной платы работников по источникам финансирования из всего списочного состава (без внешних совместителей) за счет средств бюджетов всех уровней (субсидий)')),
                ('value7', models.IntegerField(blank=True, null=True, verbose_name='Фонд начисленной заработной платы работников по источникам финансирования из всего списочного состава (без внешних совместителей) ОМС')),
                ('value8', models.IntegerField(blank=True, null=True, verbose_name='Фонд начисленной заработной платы работников по источникам финансирования из всего списочного состава (без внешних совместителей) средства от приносящей доход деятельности')),
                ('value9', models.IntegerField(blank=True, null=True, verbose_name='Фонд начисленной заработной платы работников по источникам финансирования из внешних совместителей за счет средств бюджетов всех уровней (субсидий)')),
                ('value10', models.IntegerField(blank=True, null=True, verbose_name='Фонд начисленной заработной платы работников по источникам финансирования из внешних совместителей ОМС')),
                ('value11', models.IntegerField(blank=True, null=True, verbose_name='Фонд начисленной заработной платы работников по источникам финансирования из внешних совместителей средства от приносящей доход деятельности')),
                ('r23', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r23', verbose_name='Наименование показателей')),
                ('title_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.titledoc', verbose_name='Шапка документа')),
            ],
            options={
                'verbose_name': 'VR23',
                'verbose_name_plural': 'VR23',
            },
        ),
        migrations.CreateModel(
            name='VR22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(max_length=4, verbose_name='№ строки')),
                ('value1', models.IntegerField(blank=True, null=True, verbose_name='Всего')),
                ('value2', models.IntegerField(blank=True, null=True, verbose_name='из них осуществляемые за счет средств бюджетов всех уровней (субсидий)')),
                ('r22', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r22', verbose_name='Наименование')),
                ('title_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.titledoc', verbose_name='Шапка документа')),
            ],
            options={
                'verbose_name': 'VR22',
                'verbose_name_plural': 'VR22',
            },
        ),
        migrations.CreateModel(
            name='VR21',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(max_length=4, verbose_name='№ строки')),
                ('value1', models.IntegerField(blank=True, null=True, verbose_name='Всего')),
                ('value2', models.CharField(blank=True, max_length=20, null=True, verbose_name='из них по образовательной деятельности')),
                ('r21', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r21', verbose_name='Наименование')),
                ('title_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.titledoc', verbose_name='Шапка документа')),
            ],
            options={
                'verbose_name': 'VR21',
                'verbose_name_plural': 'VR21',
            },
        ),
        migrations.CreateModel(
            name='VR20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(max_length=4, verbose_name='№ строки')),
                ('value1', models.IntegerField(blank=True, null=True, verbose_name='Всего')),
                ('value2', models.CharField(blank=True, max_length=5, null=True, verbose_name='в том числе доступные для использования воспитанниками')),
                ('r20', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r20', verbose_name='Наименование')),
                ('title_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.titledoc', verbose_name='Шапка документа')),
            ],
            options={
                'verbose_name': 'VR20',
                'verbose_name_plural': 'VR20',
            },
        ),
        migrations.CreateModel(
            name='VR2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(max_length=4, verbose_name='№ строки')),
                ('value', models.IntegerField(verbose_name='Численность воспитанников, чел')),
                ('r2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r2', verbose_name='Режим работы')),
                ('title_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.titledoc', verbose_name='Шапка документа')),
            ],
            options={
                'verbose_name': 'VR2',
                'verbose_name_plural': 'VR2',
            },
        ),
        migrations.CreateModel(
            name='VR19',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(max_length=4, verbose_name='№ строки')),
                ('value1', models.CharField(blank=True, choices=[('1', 'Да'), ('2', 'Нет')], max_length=1, null=True, verbose_name='Наличие в организации')),
                ('r19', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r19', verbose_name='Наименование')),
                ('title_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.titledoc', verbose_name='Шапка документа')),
            ],
            options={
                'verbose_name': 'VR19',
                'verbose_name_plural': 'VR19',
            },
        ),
        migrations.CreateModel(
            name='VR18',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(max_length=4, verbose_name='№ строки')),
                ('value1', models.CharField(blank=True, choices=[('1', 'Да'), ('2', 'Нет')], max_length=1, null=True, verbose_name='Наличие в организации')),
                ('r18', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r18', verbose_name='Наименование')),
                ('title_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.titledoc', verbose_name='Шапка документа')),
            ],
            options={
                'verbose_name': 'VR18',
                'verbose_name_plural': 'VR18',
            },
        ),
        migrations.CreateModel(
            name='VR17',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(max_length=4, verbose_name='№ строки')),
                ('value1', models.IntegerField(blank=True, null=True, verbose_name='Всего')),
                ('value2', models.IntegerField(blank=True, null=True, verbose_name='в том числе площадь, сданная в аренду и/или субаренду')),
                ('value3', models.IntegerField(blank=True, null=True, verbose_name='Площадь на правах собственности')),
                ('value4', models.IntegerField(blank=True, null=True, verbose_name='Площадь в оперативном управлении')),
                ('value5', models.IntegerField(blank=True, null=True, verbose_name='Арендованная площадь')),
                ('value6', models.IntegerField(blank=True, null=True, verbose_name='Площадь в другой форме владения')),
                ('r17', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r17', verbose_name='Наименование показателей')),
                ('title_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.titledoc', verbose_name='Шапка документа')),
            ],
            options={
                'verbose_name': 'VR17',
                'verbose_name_plural': 'VR17',
            },
        ),
        migrations.CreateModel(
            name='VR16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(max_length=4, verbose_name='№ строки')),
                ('value1', models.CharField(blank=True, choices=[('1', 'Да'), ('2', 'Нет')], max_length=1, null=True, verbose_name='Наличие в организации')),
                ('r16', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r16', verbose_name='Наименование')),
                ('title_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.titledoc', verbose_name='Шапка документа')),
            ],
            options={
                'verbose_name': 'VR16',
                'verbose_name_plural': 'VR16',
            },
        ),
        migrations.CreateModel(
            name='VR15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Здание №1', max_length=20, verbose_name='Здание №')),
                ('str', models.CharField(max_length=4, verbose_name='№ строки')),
                ('value1', models.CharField(blank=True, choices=[('1', 'Да'), ('2', 'Нет')], default='2', max_length=1, null=True, verbose_name='каменные')),
                ('value2', models.CharField(blank=True, choices=[('1', 'Да'), ('2', 'Нет')], max_length=1, null=True, verbose_name='кирпичные')),
                ('value3', models.CharField(blank=True, choices=[('1', 'Да'), ('2', 'Нет')], max_length=1, null=True, verbose_name='панельные')),
                ('value4', models.CharField(blank=True, choices=[('1', 'Да'), ('2', 'Нет')], max_length=1, null=True, verbose_name='блочные')),
                ('value5', models.CharField(blank=True, choices=[('1', 'Да'), ('2', 'Нет')], max_length=1, null=True, verbose_name='деревянные')),
                ('value6', models.CharField(blank=True, choices=[('1', 'Да'), ('2', 'Нет')], max_length=1, null=True, verbose_name='монолитные')),
                ('value7', models.CharField(blank=True, choices=[('1', 'Да'), ('2', 'Нет')], max_length=1, null=True, verbose_name='смешанные')),
                ('value8', models.CharField(blank=True, choices=[('1', 'Да'), ('2', 'Нет')], max_length=1, null=True, verbose_name='из прочих стеновых материалов')),
                ('title_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.titledoc', verbose_name='Шапка документа')),
            ],
            options={
                'verbose_name': 'VR15',
                'verbose_name_plural': 'VR15',
            },
        ),
        migrations.CreateModel(
            name='VR14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(max_length=4, verbose_name='№ строки')),
                ('value1', models.IntegerField(blank=True, null=True, verbose_name='Всего')),
                ('value2', models.IntegerField(blank=True, null=True, verbose_name='Оборудовано водопроводом')),
                ('value3', models.IntegerField(blank=True, null=True, verbose_name='Оборудовано водоотведением (канализацией)')),
                ('value4', models.IntegerField(blank=True, null=True, verbose_name='Оборудовано центральным отоплением')),
                ('value5', models.IntegerField(blank=True, null=True, verbose_name='Оборудовано системой видеонаблюдения')),
                ('value6', models.IntegerField(blank=True, null=True, verbose_name='Требует капитального ремонта')),
                ('value7', models.IntegerField(blank=True, null=True, verbose_name='Находится в аварийном состоянии')),
                ('value8', models.IntegerField(blank=True, null=True, verbose_name='Имеет охрану')),
                ('value9', models.IntegerField(blank=True, null=True, verbose_name='Оборудовано автоматической пожарной сигнализацией')),
                ('value10', models.IntegerField(blank=True, null=True, verbose_name='Имеет дымовые извещатели')),
                ('value11', models.IntegerField(blank=True, null=True, verbose_name='Имеет пожарные краны и рукава')),
                ('value12', models.IntegerField(blank=True, null=True, verbose_name='Оборудовано кнопкой тревожной сигнализации')),
                ('value13', models.IntegerField(blank=True, null=True, verbose_name='Доступно для маломобильных групп населения')),
                ('value14', models.IntegerField(blank=True, null=True, verbose_name='Скорость Интернета ниже 256 Кбит/сек')),
                ('value15', models.IntegerField(blank=True, null=True, verbose_name='Скорость Интернета 256 - 511 Кбит/сек')),
                ('value16', models.IntegerField(blank=True, null=True, verbose_name='Скорость Интернета 512 Кбит/сек - 999 Кбит/сек')),
                ('value17', models.IntegerField(blank=True, null=True, verbose_name='Скорость Интернета 1.0 - 1.9 Мбит/сек')),
                ('value18', models.IntegerField(blank=True, null=True, verbose_name='Скорость Интернета 2.0 - 29.9 Мбит/сек')),
                ('value19', models.IntegerField(blank=True, null=True, verbose_name='Скорость Интернета 30.0 - 49.9 Мбит/сек')),
                ('value20', models.IntegerField(blank=True, null=True, verbose_name='Скорость Интернета 50.0 - 99.9 Мбит/сек')),
                ('value21', models.IntegerField(blank=True, null=True, verbose_name='Скорость Интернета 100 Мбит/сек и выше')),
                ('r14', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r14', verbose_name='Наименование показателей')),
                ('title_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.titledoc', verbose_name='Шапка документа')),
            ],
            options={
                'verbose_name': 'VR14',
                'verbose_name_plural': 'VR14',
            },
        ),
        migrations.CreateModel(
            name='VR13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(max_length=4, verbose_name='№ строки')),
                ('value1', models.IntegerField(verbose_name='Число ставок по штату, ед.')),
                ('value2', models.IntegerField(verbose_name='Всего фактически занято')),
                ('value3', models.IntegerField(verbose_name='Фактически занято работниками списочного состава')),
                ('value4', models.IntegerField(verbose_name='Численность работников на начало отчетного года (без внешних совместителей и работающих по договорам гражданско- правового характера) ')),
                ('value5', models.IntegerField(verbose_name='Всего принято работников')),
                ('value6', models.IntegerField(verbose_name='Принято работников, являющимися выпускниками со средним профессиональным образованием по программам подготовки специалистов среднего звена')),
                ('value7', models.IntegerField(verbose_name='Принято работников, являющимися выпускниками с высшим образованием')),
                ('value8', models.IntegerField(verbose_name='Всего выбыло работников')),
                ('value9', models.IntegerField(verbose_name='Выбыло работников по собственному желанию')),
                ('value10', models.IntegerField(verbose_name='Численность работников на конец отчетного года (без совместителей и работающих по договорам гражданско-правового характера)')),
                ('value11', models.IntegerField(verbose_name='Число вакантных должностей')),
                ('r13', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r13', verbose_name='Наименование показателей')),
                ('title_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.titledoc', verbose_name='Шапка документа')),
            ],
            options={
                'verbose_name': 'VR13',
                'verbose_name_plural': 'VR13',
            },
        ),
        migrations.CreateModel(
            name='VR12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(max_length=4, verbose_name='№ строки')),
                ('value1', models.IntegerField(verbose_name='Всего')),
                ('value2', models.IntegerField(verbose_name=' них женщины')),
                ('r12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r12', verbose_name='Наименование показателей')),
                ('title_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.titledoc', verbose_name='Шапка документа')),
            ],
            options={
                'verbose_name': 'VR12',
                'verbose_name_plural': 'VR12',
            },
        ),
        migrations.CreateModel(
            name='VR11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(max_length=4, verbose_name='№ строки')),
                ('value1', models.IntegerField(verbose_name='Всего с общим стажем')),
                ('value2', models.IntegerField(verbose_name='с общим стажем до 3 лет')),
                ('value3', models.IntegerField(verbose_name='с общим стажем от 3 до 5 лет')),
                ('value4', models.IntegerField(verbose_name='с общим стажем от 5 до 10 лет')),
                ('value5', models.IntegerField(verbose_name='с общим стажем от 10 до 15 лет')),
                ('value6', models.IntegerField(verbose_name='с общим стажем от 15 до 20 лет')),
                ('value7', models.IntegerField(verbose_name='с общим стажем от 20 и более лет')),
                ('value8', models.IntegerField(verbose_name='Из общей численности работников имеют педагогический стаж (всего)')),
                ('value9', models.IntegerField(verbose_name='с педагогическим стажем до 3 лет')),
                ('value10', models.IntegerField(verbose_name='с педагогическим стажем от 3 до 5 лет')),
                ('value11', models.IntegerField(verbose_name='с педагогическим стажем от 5 до 10 лет')),
                ('value12', models.IntegerField(verbose_name='с педагогическим стажем от 10 до 15 лет')),
                ('value13', models.IntegerField(verbose_name='с педагогическим стажем от 15 до 20 лет')),
                ('value14', models.IntegerField(verbose_name='с педагогическим стажем от 20 и более лет')),
                ('r11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r10r11', verbose_name='Наименование показателей')),
                ('title_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.titledoc', verbose_name='Шапка документа')),
            ],
            options={
                'verbose_name': 'VR11',
                'verbose_name_plural': 'VR11',
            },
        ),
        migrations.CreateModel(
            name='VR10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(max_length=4, verbose_name='№ строки')),
                ('value1', models.IntegerField(verbose_name='Всего')),
                ('value2', models.IntegerField(verbose_name='моложе 25 лет')),
                ('value3', models.IntegerField(verbose_name='25-29')),
                ('value4', models.IntegerField(verbose_name='30-34')),
                ('value5', models.IntegerField(verbose_name='35-39')),
                ('value6', models.IntegerField(verbose_name='40-44')),
                ('value7', models.IntegerField(verbose_name='45-49')),
                ('value8', models.IntegerField(verbose_name='50-54')),
                ('value9', models.IntegerField(verbose_name='55-59')),
                ('value10', models.IntegerField(verbose_name='60-64')),
                ('value11', models.IntegerField(verbose_name='65 и старше')),
                ('r10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.r10r11', verbose_name='Наименование показателей')),
                ('title_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.titledoc', verbose_name='Шапка документа')),
            ],
            options={
                'verbose_name': 'VR10',
                'verbose_name_plural': 'VR10',
            },
        ),
        migrations.CreateModel(
            name='VR1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_build', models.CharField(choices=[('5', 'дошкольная образовательная организация;'), ('2', 'обособленное подразделение (филиал) дошкольной образовательной организации;'), ('3', 'обособленное подразделение (филиал) общеобразовательной организации;'), ('15', 'обособленное подразделение (филиал) профессиональной образовательной организации;'), ('6', 'обособленное подразделение (филиал) образовательной организации высшего образования;'), ('13', 'подразделения (группы), осуществляющие образовательную деятельность по образовательным программам дошкольного образования, присмотр и уход за детьми; организованные при общеобразовательной организации;'), ('16', 'подразделения (группы), осуществляющие образовательную деятельность по образовательным программам дошкольного образования, присмотр и уход за детьми; организованные при профессиональной образовательной организации;'), ('7', 'подразделения (группы), осуществляющие образовательную деятельность по образовательным программам дошкольного образования, присмотр и уход за детьми; организованные при образовательной организации высшего образования;'), ('8', 'подразделения (группы), осуществляющие образовательную деятельность по образовательным программам дошкольного образования, присмотр и уход за детьми; организованные при организации дополнительного образования детей;'), ('9', 'подразделения (группы), созданные при ином юридическом лице или юридическое лицо, осуществляющее образовательную деятельность по образовательным программам дошкольного образования, присмотр и уход за детьми (организации здравоохранения, социального обслуживания, науки, культуры и другие, осуществляющие образовательную деятельность по образовательным программам дошкольного образования, присмотр и уход за детьми в качестве дополнительной к своей основной деятельности);'), ('14', 'организация, осуществляющая присмотр и уход за детьми, без осуществления образовательной деятельности по программам дошкольного образования (организации, осуществляющие присмотр и уход за детьми в качестве как основной, так и дополнительной к своей основной деятельности). В данных организациях обеспечивается комплекс мер по организации питания и хозяйственно-бытового обслуживания детей, обеспечению соблюдения ими личной гигиены и режима дня;'), ('17', 'индивидуальный предприниматель.')], default='5', max_length=2, verbose_name='Тип организации')),
                ('type_city', models.CharField(choices=[('1', 'городская местность;'), ('2', 'сельская местность.')], default='1', max_length=1, verbose_name='Тип поселения')),
                ('status_build', models.CharField(choices=[('1', 'функционирует;'), ('2', 'организация временно не работает из-за проведения капитального ремонта или реконструкции;'), ('3', 'организация функционирует и одно из зданий находится в аварийном состоянии;'), ('4', 'деятельность приостановлена;'), ('5', 'организация функционирует и одно из зданий требует капитального ремонта.')], default='1', max_length=1, verbose_name='Статус организации')),
                ('work_days', models.CharField(choices=[('2', 'пятидневный;'), ('3', 'шестидневный;'), ('14', 'семидневный (круглосуточно).')], default='2', max_length=2, verbose_name='Режим функционирования')),
                ('social_unit', models.CharField(choices=[('1', 'наличие в дошкольной образовательной организации коллегиального органа управления с участием общественности (родители, работодатели);'), ('2', 'отсутствие в дошкольной образовательной организации коллегиального органа управления с участием общественности.')], default='2', max_length=1, verbose_name='Наличие коллегиального органа с участием общественности')),
                ('title_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.titledoc', verbose_name='Шапка документа')),
            ],
            options={
                'verbose_name': 'VR1',
                'verbose_name_plural': 'VR1',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_name', models.CharField(blank=True, help_text='Отчество пользователя', max_length=50, verbose_name='Отчество')),
                ('age', models.IntegerField(blank=True, help_text='Полных лет пользователя', null=True, verbose_name='Возраст')),
                ('city', models.CharField(blank=True, help_text='Город, в котором живет пользователь', max_length=50, verbose_name='Город')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Мужской'), ('W', 'Женский')], default='M', help_text='Пол пользователя', max_length=1, verbose_name='Пол')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='UsersEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reg', models.DateField(help_text='Дата регистрации на меропрятии', null=True, verbose_name='Дата регистрации')),
                ('link_certificate', models.FileField(blank=True, help_text='Сертификат участника мероприятия', null=True, upload_to='', verbose_name='Сертификат')),
                ('rating', models.IntegerField(blank=True, help_text='Занимеемое место на мероприятии', null=True, verbose_name='Занимеемое место')),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.event', verbose_name='Событие в котором учавствует пользователь')),
                ('id_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.status', verbose_name='Статус участника в мероприятии')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участник события')),
            ],
            options={
                'verbose_name': 'Событие и участник',
                'verbose_name_plural': 'События и участники',
                'unique_together': {('id_event', 'id_user')},
            },
        ),
    ]
