# Generated by Django 4.1.7 on 2023-05-10 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='usersevents',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usersevents',
            name='id_event',
        ),
        migrations.RemoveField(
            model_name='usersevents',
            name='id_status',
        ),
        migrations.RemoveField(
            model_name='usersevents',
            name='id_user',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='UsersEvents',
        ),
    ]
