# Generated by Django 4.1.7 on 2023-05-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_builds_fio_builds_adres_builds_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builds',
            name='FIO',
            field=models.CharField(blank=True, max_length=300, verbose_name='ФИО заведующего'),
        ),
        migrations.AlterField(
            model_name='builds',
            name='adres',
            field=models.TextField(blank=True, max_length=300, verbose_name='Юридический адрес'),
        ),
    ]
