# Generated by Django 4.1.7 on 2023-05-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_builds_fio_alter_builds_adres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='builddocs',
            name='link',
        ),
        migrations.AddField(
            model_name='builds',
            name='link',
            field=models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='builds',
            name='FIO',
            field=models.CharField(blank=True, max_length=300, verbose_name='ФИО руководителя'),
        ),
    ]
