# Generated by Django 4.1.7 on 2023-05-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='builds',
            name='link',
        ),
        migrations.AddField(
            model_name='builddocs',
            name='link',
            field=models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='Документ'),
        ),
    ]
