# Generated by Django 4.1.7 on 2023-05-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_builds_link_builddocs_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='builddocs',
            name='link',
        ),
        migrations.AddField(
            model_name='builds',
            name='link',
            field=models.FileField(default='docs/default/template.xlsx', upload_to='docs/', verbose_name='Документ'),
        ),
    ]
