# Generated by Django 4.1.7 on 2023-06-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_builddocs_link_builds_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='builds',
            name='email',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AddField(
            model_name='builds',
            name='site',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес сайта организации'),
        ),
        migrations.AddField(
            model_name='builds',
            name='students',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество учеников'),
        ),
        migrations.AddField(
            model_name='builds',
            name='telephone',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='builds',
            name='workers',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество педогогических работников'),
        ),
        migrations.AlterField(
            model_name='builds',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Логотип'),
        ),
    ]
