from django.contrib import admin

from .import models

admin.site.register(models.Builds)
admin.site.register(models.TitleDoc)
admin.site.register(models.R2)
admin.site.register(models.R3)
admin.site.register(models.R4R5R6)
admin.site.register(models.R7)
admin.site.register(models.R8)
admin.site.register(models.R9)
admin.site.register(models.R10R11)
admin.site.register(models.R12)
admin.site.register(models.R13)
admin.site.register(models.R14)
admin.site.register(models.R16)
admin.site.register(models.R17)
admin.site.register(models.R18)
admin.site.register(models.R19)
admin.site.register(models.R20)
admin.site.register(models.R21)
admin.site.register(models.R22)
admin.site.register(models.R23)
admin.site.register(models.R24)
admin.site.register(models.R25)

admin.site.register(models.VR1)
admin.site.register(models.VR2)
admin.site.register(models.VR3)
admin.site.register(models.VR4)
admin.site.register(models.VR5)
admin.site.register(models.VR6)
admin.site.register(models.VR7)
admin.site.register(models.VR8)
admin.site.register(models.VR9)
admin.site.register(models.VR10)
admin.site.register(models.VR11)
admin.site.register(models.VR12)
admin.site.register(models.VR13)
admin.site.register(models.VR14)
admin.site.register(models.VR15)
admin.site.register(models.VR16)
admin.site.register(models.VR17)
admin.site.register(models.VR18)
admin.site.register(models.VR19)
admin.site.register(models.VR20)
admin.site.register(models.VR21)
admin.site.register(models.VR22)
admin.site.register(models.VR23)
admin.site.register(models.VR24)
admin.site.register(models.VR25)





